// Get Navigation Metadata
export const GET_NAVIGATION_META_DATA_INIT = "GET_NAVIGATION_META_DATA_INIT";
export const GET_NAVIGATION_META_DATA_SUCCESS =
  "GET_NAVIGATION_META_DATA_SUCCESS";
export const GET_NAVIGATION_META_DATA_FAIL = "GET_NAVIGATION_META_DATA_FAIL";

// User Preferences
export const GET_DEFAULT_USER_PREFERENCE_INIT =
  "GET_DEFAULT_USER_PREFERENCE_INIT";
export const GET_DEFAULT_USER_PREFERENCE_SUCCESS =
  "GET_DEFAULT_USER_PREFERENCE_SUCCESS";
export const GET_DEFAULT_USER_PREFERENCE_FAIL =
  "GET_DEFAULT_USER_PREFERENCE_FAIL";

// Feature Flags
export const GET_FEATURE_FLAG_INIT = "GET_FEATURE_FLAG_INIT";
export const GET_FEATURE_FLAG_SUCCESS = "GET_FEATURE_FLAG_SUCCESS";
export const GET_FEATURE_FLAG_FAIL = "GET_FEATURE_FLAG_FAIL";
